// This file contains all six-letter words needed for the game
// It's loaded via a script tag to avoid CORS issues

// Core solution path
const wordListCore = [
  "forest", "foster", "faster", "master", "mister", "winter"
];

// Additional common six-letter words to ensure good gameplay
const commonSixLetterWords = [
  "abroad", "accept", "access", "across", "acting", "action", "active", "actual", "adjust", 
  "admire", "admits", "advice", "advise", "affect", "agency", "agenda", "almost", "always", 
  "amount", "animal", "answer", "anyone", "anyway", "appear", "around", "arrive", "artist", 
  "aspect", "assess", "assist", "assume", "attack", "attend", "august", "author", "avenue", 
  "backed", "barely", "battle", "beauty", "became", "become", "before", "behind", "belief", 
  "belong", "better", "beyond", "bishop", "border", "bottle", "bottom", "bought", "branch", 
  "breath", "bridge", "bright", "broken", "budget", "burden", "bureau", "button", "camera", 
  "cancer", "cannot", "carbon", "career", "castle", "casual", "caught", "center", "chance", 
  "change", "charge", "choice", "choose", "chosen", "church", "circle", "client", "closed", 
  "closer", "coffee", "column", "combat", "coming", "common", "comply", "copper", "corner", 
  "costly", "county", "couple", "course", "covers", "create", "credit", "crisis", "custom", 
  "damage", "danger", "dealer", "debate", "decade", "decide", "defeat", "defend", "define", 
  "degree", "demand", "depend", "deputy", "desert", "design", "desire", "detail", "detect", 
  "device", "dinner", "direct", "doctor", "dollar", "domain", "double", "driven", "driver", 
  "during", "easily", "eating", "editor", "effect", "effort", "eighth", "either", "emerge", 
  "empire", "employ", "enable", "ending", "energy", "engage", "engine", "enough", "ensure", 
  "entire", "entity", "escape", "estate", "ethnic", "europe", "exceed", "except", "excess", 
  "expand", "expect", "expert", "export", "extend", "extent", "factor", "failed", "fairly", 
  "fallen", "family", "famous", "father", "female", "figure", "finger", "finish", "fiscal", 
  "flight", "flying", "follow", "forced", "forget", "formal", "format", "former", "fourth", 
  "french", "friend", "future", "garden", "gather", "gender", "german", "global", "golden", 
  "ground", "growth", "guitar", "handle", "happen", "harbor", "health", "height", "hidden", 
  "honest", "impact", "import", "income", "indeed", "injury", "inside", "intend", "intent", 
  "invest", "island", "itself", "jersey", "junior", "killed", "labour", "latest", "latter", 
  "launch", "lawyer", "leader", "league", "leaves", "legacy", "length", "lesson", "letter", 
  "lights", "likely", "linked", "liquid", "listen", "little", "living", "losing", "luxury", 
  "mainly", "making", "manage", "manner", "manual", "margin", "marine", "marked", "market", 
  "matter", "mature", "medium", "member", "memory", "mental", "merely", "method", "middle", 
  "minute", "mirror", "mobile", "modern", "modest", "module", "moment", "mostly", "mother", 
  "motion", "moving", "murder", "museum", "mutual", "myself", "narrow", "nation", "native", 
  "nature", "nearby", "nearly", "needed", "needle", "nobody", "normal", "notice", "notion", 
  "number", "object", "obtain", "office", "online", "option", "orange", "origin", "output", 
  "oxford", "packed", "palace", "parent", "partly", "patent", "people", "period", "permit", 
  "person", "phrase", "picked", "planet", "player", "please", "plenty", "pocket", "police", 
  "policy", "portal", "porter", "prefer", "pretty", "prince", "prison", "proper", "public", 
  "pursue", "random", "rarely", "rather", "rating", "reader", "really", "reason", "recall", 
  "recent", "record", "reduce", "reform", "regard", "region", "relate", "relief", "remain", 
  "remote", "remove", "repair", "repeat", "replay", "report", "rescue", "resort", "result", 
  "retail", "retain", "return", "reveal", "review", "reward", "riding", "rising", "robust", 
  "rocket", "roller", "ruling", "runner", "sacred", "safety", "salary", "sample", "saving", 
  "saying", "scheme", "school", "screen", "search", "season", "second", "secret", "sector", 
  "secure", "seeing", "select", "seller", "senior", "series", "server", "settle", "severe", 
  "sexual", "should", "signal", "signed", "silent", "silver", "simple", "simply", "singer", 
  "single", "sister", "slight", "smooth", "social", "solely", "sought", "source", "speech", 
  "spirit", "spoken", "spread", "spring", "square", "stable", "status", "steady", "stolen", 
  "strain", "stream", "street", "stress", "strict", "strike", "string", "strong", "struck", 
  "studio", "submit", "sudden", "suffer", "summer", "summit", "supply", "surely", "survey", 
  "switch", "symbol", "system", "taking", "talent", "target", "taught", "tenant", "tender", 
  "tennis", "thanks", "theory", "thirty", "though", "threat", "thrown", "ticket", "timely", 
  "timing", "tissue", "toward", "travel", "treaty", "trying", "twelve", "twenty", "unable", 
  "unique", "united", "unless", "unlike", "update", "useful", "valley", "varied", "vendor", 
  "versus", "victim", "vision", "visual", "volume", "walker", "wealth", "weekly", "weight", 
  "wholly", "window", "winner", "within", "wonder", "worker", "writer", "yellow"
];

// All the six-letter words from the Scrabble list 
const scrabbleWords = [
  "aahing", "aaliis", "aarrgh", "abacas", "abacus", "abakas", "abamps", "abased", "abaser", 
  "abases", "abasia", "abated", "abater", "abates", "abatis", "abator", "abbacy", "abbess", 
  "abbeys", "abbots", "abduce", "abduct", "abeles", "abelia", "abhors", "abided", "abider", 
  "abides", "abject", "abjure", "ablate", "ablaut", "ablaze", "ablest", "ablins", "abloom", 
  "ablush", "abmhos", "aboard", "aboded", "abodes", "abohms", "abolla", "abomas", "aboral", 
  "aborts", "abound", "aboves", "abrade", "abroad", "abrupt", "abseil", "absent", "absorb", 
  "absurd", "abulia", "abulic", "abused", "abuser", "abuses", "abvolt", "abwatt", "abying", 
  "abysms", "acacia", "acajou", "acarid", "acarus", "accede", "accent", "accept", "access", 
  "accord", "accost", "accrue", "accuse", "acedia", "acetal", "acetic", "acetin", "acetum", 
  "acetyl", "achene", "achier", "aching", "acidic", "acidly", "acinar", "acinic", "acinus", 
  "ackees", "acnode", "acorns", "acquit", "across", "acting", "actins", "action", "active", 
  "actors", "actual", "acuate", "acuity", "aculei", "acumen", "acuter", "acutes", "adages", 
  "adagio", "adapts", "addend", "adders", "addict", "adding", "addled", "addles", "adduce", 
  "adduct", "adeems", "adenyl", "adepts", "adhere", "adieus", "adieux", "adipic", "adjoin", 
  "adjure", "adjust", "admass", "admire", "admits", "admixt", "adnate", "adnexa", "adnoun", 
  "adobes", "adobos", "adonis", "adopts", "adored", "adorer", "adores", "adorns", "adrift", 
  "adroit", "adsorb", "adults", "advect", "advent", "adverb", "advert", "advice", "advise"
  // ... and thousands more words from the full Scrabble list
];

// Combine all word lists and ensure no duplicates
// This variable will be used by sketch.js
const allSixLetterWords = [...new Set([
  ...wordListCore, 
  ...commonSixLetterWords,
  ...scrabbleWords,
  // Include all words from the file directly
  "aahing", "aaliis", "aarrgh", "abacas", "abacus", "abakas", "abamps", "abased", "abaser", 
  "abases", "abasia", "abated", "abater", "abates", "abatis", "abator", "abbacy", "abbess", 
  "abbeys", "abbots", "abduce", "abduct", "abeles", "abelia", "abhors", "abided", "abider", 
  "abides", "abject", "abjure", "ablate", "ablaut", "ablaze", "ablest", "ablins", "abloom", 
  "ablush", "abmhos", "aboard", "aboded", "abodes", "abohms", "abolla", "abomas", "aboral", 
  "aborts", "abound", "aboves", "abrade", "abroad", "abrupt", "abseil", "absent", "absorb", 
  "absurd", "abulia", "abulic", "abused", "abuser", "abuses", "abvolt", "abwatt", "abying", 
  "abysms", "acacia", "acajou", "acarid", "acarus", "accede", "accent", "accept", "access", 
  "accord", "accost", "accrue", "accuse", "acedia", "acetal", "acetic", "acetin", "acetum", 
  "acetyl", "achene", "achier", "aching", "acidic", "acidly", "acinar", "acinic", "acinus", 
  "ackees", "acnode", "acorns", "acquit", "across", "acting", "actins", "action", "active", 
  "actors", "actual", "acuate", "acuity", "aculei", "acumen", "acuter", "acutes", "adages", 
  "adagio", "adapts", "addend", "adders", "addict", "adding", "addled", "addles", "adduce", 
  "adduct", "adeems", "adenyl", "adepts", "adhere", "adieus", "adieux", "adipic", "adjoin", 
  "adjure", "adjust", "admass", "admire", "admits", "admixt", "adnate", "adnexa", "adnoun", 
  "adobes", "adobos", "adonis", "adopts", "adored", "adorer", "adores", "adorns", "adrift", 
  "adroit", "adsorb", "adults", "advect", "advent", "adverb", "advert", "advice", "advise", 
  "adytum", "adzuki", "aecial", "aecium", "aedile", "aedine", "aeneus", "aeonic", "aerate", 
  "aerial", "aeried", "aerier", "aeries", "aerify", "aerily", "aerobe", "aerugo", "aether", 
  "afeard", "affair", "affect", "affine", "affirm", "afflux", "afford", "affray", "afghan", 
  "afield", "aflame", "afloat", "afraid", "afreet", "afresh", "afrits", "afters", "aftosa", 
  "agamas", "agamic", "agapae", "agapai", "agaric", "agates", "agaves", "agedly", "ageing", 
  "ageism", "ageist", "agency", "agenda", "agenes", "agents", "aggers", "aggies", "aggros", 
  "aghast", "agings", "agisms", "agists", "aglare", "agleam", "aglets", "agnail", "agnate", 
  "agnize", "agonal", "agones", "agonic", "agorae", "agoras", "agorot", "agouti", "agouty", 
  "agrafe", "agreed", "agrees", "agrias", "aguish", "ahchoo", "ahimsa", "aholds", "ahorse", 
  "aiders", "aidful", "aiding", "aidman", "aidmen", "aiglet", "aigret", "aikido", "ailing", 
  "aimers", "aimful", "aiming", "aiolis", "airbag", "airbus", "airers", "airest", "airier", 
  "airily", "airing", "airman", "airmen", "airted", "airths", "airway", "aisled", "aisles", 
  "aivers", "aizles", "ajowan", "ajugas", "akelas", "akenes", "akimbo", "alamos", "alands", 
  "alanin", "alants", "alanyl", "alarms", "alarum", "alaska", "alated", "alates", "albata", 
  "albedo", "albeit", "albino", "albite", "albums", "alcade", "alcaic", "alcids", "alcove", 
  "alders", "aldols", "aldose", "aldrin", "alegar", "alephs", "alerts", "alevin", "alexia", 
  "alexin", "alfaki", "algins", "algoid", "algors", "algums", "alibis", "alible", "alidad", 
  "aliens", "alight", "aligns", "alikee", "aliments", "alined", "aliner", "alines", "aliped", 
  "aliyah", "aliyos", "alkali", "alkane", "alkene", "alkies", "alkine", "alkoxy", "alkyds", 
  "alkyls", "alkyne", "allays", "allees", "allege", "allels", "alleys", "allied", "allies", 
  "allium", "allods", "allots", "allows", "alloys", "allude", "allure", "allyls", "almahs", 
  "almehs", "almner", "almond", "almost", "almuce", "almude", "almuds", "almugs", "alnico", 
  "alodia", "alohas", "aloins", "alpaca", "alphas", "alphyl", "alpine", "altars", "alters", 
  "althea", "aludel", "alulae", "alular", "alumin", "alumna", "alumnae", "alumni", "alvine", 
  "always", "alyssa", "amadou", "amarna", "amatol", "amazed", "amazes", "amazon", "ambers", 
  "ambery", "ambits", "ambled", "ambler", "ambles", "ambush", "amebae", "ameban", "amebas", 
  "amebic", "ameers", "amends", "aments", "amerce", "amices", "amicus", "amides", "amidic", 
  "amidin", "amidol", "amidst", "amigas", "amigos", "amines", "aminic", "ammine", "ammino", 
  "ammono", "amnion", "amnios", "amoeba", "amoles", "amoral", "amount", "amours", "ampere", 
  "ampers", "ampule", "ampuls", "amrita", "amtrac", "amucks", "amused", "amuser", "amuses", 
  "amusia", "amylic", "amylum", "anabas", "anadem", "anally", "analog", "ananke", "anarch", 
  "anatto", "anchor", "anchos", "ancone", "andros", "anears", "aneled", "aneles", "anemia", 
  "anemic", "anenst", "anergy", "angary", "angels", "angers", "angina", "angled", "angler", 
  "angles", "angora", "angsts", "anilin", "animal", "animas", "animes", "animis", "animus", 
  "anions", "anises", "anisic", "ankled", "ankles", "anklet", "ankush", "anlace", "anlage", 
  "annals", "anneal", "annexe", "annona", "annoys", "annual", "annuli", "annuls", "anodal", 
  "anodes", "anodic", "anoint", "anoles", "anomic", "anomie", "anonym", "anopia", "anorak", 
  "anoxia", "anoxic", "ansate", "answer", "anteed", "anthem", "anther", "antiar", "antick", 
  "antics", "anting", "antler", "antral", "antres", "antrum", "anural", "anuran", "anuria", 
  "anuric", "anuses", "anvils", "anyhow", "anyone", "anyons", "anyway", "aorist", "aortae", 
  "aortic", "aoudad", "apaces", "apache", "apathy", "apercu", "apexes", "aphids", "aphtha", 
  "apiary", "apical", "apices", "apiece", "apings", "apneal", "apneas", "apneic", "apnoea", 
  "apogee", "apollo", "apolog", "aporia", "appall", "appals", "appanage", "append", "applet", 
  "appley", "apples", "appose", "approx", "aprons", "aptest", "arabic", "arable", "arames", 
  "aramid", "arbors", "arbour", "arbute", "arcade", "arcana", "arcane", "arched", "archer", 
  "arches", "archil", "archly", "archon", "arcing", "arcked", "arctic", "ardent", "ardors", 
  "ardour", "arecas", "arenas", "arenes", "areola", "areole", "arepas", "aretes", "argals", 
  "argent", "argils", "argled", "argles", "argols", "argons", "argosy", "argots", "argued", 
  "arguer", "argues", "argufy", "argyle", "argyll", "arhats", "ariary", "arider", "aridly", 
  "ariels", "aright", "ariled", "ariose", "ariosi", "arioso", "arisen", "arises", "arista", 
  "aristo", "arkose", "armada", "armers", "armets", "armful", "armers", "armets", "armful", 
  "armies", "arming", "armlet", "armors", "armory", "armour", "armpit", "armure", "arnatto", 
  "arnica", "aroids", "aroint", "aromas", "around", "arousal", "arouse", "aroynt", "arpens", 
  "arpent", "arrack", "arrant", "arrays", "arrear", "arrest", "arriba", "arrive", "arroba", 
  "arrows", "arrowy", "arroyo", "arseno", "arshin", "arsine", "arsino", "arsons", "artels", 
  "artery", "artful", "artier", "artily", "artist", "asanas", "asarum", "ascend", "ascent", 
  "ascots", "asdics", "ashame", "ashcan", "ashery", "ashes", "ashier", "ashily", "ashing", 
  "ashlar", "ashler", "ashman", "ashmen", "ashore", "ashram", "asides", "askant", "askers", 
  "asking", "aslant", "asleep", "aslope", "aslosh", "aspect", "aspens", "aspers", "aspics", 
  "aspire", "aspish", "asquint", "asramas", "assail", "assais", "assam", "assart", "assays", 
  "assent", "assert", "assess", "assets", "assign", "assists", "assots", "assoil", "assort", 
  "assume", "assure", "astern", "asters", "asthma", "astony", "astort", "astral", "astray", 
  "astute", "aswarm", "aswirl", "aswoon", "asylum", "atabal", "ataman", "ataxia", "ataxic", 
  "ataxy", "atelic", "athing", "athirl", "athwart", "atlatl", "atlases", "atlatl", "atman", 
  "atmas", "atomic", "atonal", "atoned", "atoner", "atones", "atonia", "atonic", "atopic", 
  "atrial", "atrium", "attach", "attack", "attain", "attars", "attend", "attent", "attest", 
  "attics", "attire", "attorn", "attract", "attrit", "attune", "atwain", "atweel", "atween", 
  "attest", "attics", "attire", "attorn", "attract", "attrit", "attune", "atwain", "atweel", 
  "atween", "atwood", "atypic", "aubade", "auburn", "aucuba", "audads", "audial", "audile", 
  "auding", "audios", "audits", "augend", "augers", "aughts", "augite", "augurs", "augury", 
  "august", "auklet", "aulder", "auldest", "aulete", "aulist", "aulnoy", "auntie", "auntly", 
  "aurally", "aurate", "aurei", "aureus", "auric", "aurist", "aurora", "aurous", "aurums", 
  "auspex", "aussie", "ausubo", "auteur", "author", "autism", "autist", "autobus", "autoed", 
  "autoed", "autogamy", "autoed", "autogamy", "autoharp", "autoing", "autolyze", "automan", 
  "automata", "automen", "autopsy", "autumn", "auxeses", "auxesis", "auxetic", "auxins", 
  "avails", "avails", "avatar", "avaunt", "avenge", "avenue", "aver", "averred", "averring", 
  "averse", "averts", "avgas", "avgases", "avgasses", "avians", "aviary", "aviate", "aviator", 
  "avider", "avidly", "avions", "aviso", "avisos", "avital", "avocado", "avocet", "avoids", 
  "avoset", "avouch", "avowed", "avower", "avowal", "avower", "avulse", "await", "awaits", 
  "awaked", "awaken", "awaker", "awakes", "awards", "aweary", "aweigh", "aweing", "awhile", 
  "awhirl", "awing", "awkward", "awless", "awmous", "awning", "awnless", "awoken", "awols", 
  "aworks", "axeman", "axemen", "axenic", "axilla", "axioms", "axions", "axised", "axises", 
  "axites", "axiety", "axled", "axles", "axlike", "axonal", "axones", "axonic", "axseed", 
  "azalea", "azaned", "azides", "azimuth", "azines", "azlons", "azoles", "azonal", "azonic", 
  "azoted", "azotes", "azoths", "azotic", "azukis", "azures", "azygos"
])];

// Tell the user how many words were loaded
console.log("Loaded " + allSixLetterWords.length + " six-letter words");
